### ISSUE TITLE
Script Kiddy Issues

### ISSUE THREAD

**Issue by JesusIsHigh** [kawaxi/Kali-Setup#5]
Hey,

Apologies I'm a new script kiddy got no clue what I'm doing. I did git clone https://github.com/kawaxi/kali-setup now what? xD Sorry I'm very basic

Many Thanks,

If it's easier for you you can DM me on twitter @JesusIsHigh

**Comment by kawaxi** [comment]
Do something like  : bash Start -h on the cloned folder.
